Change return type for conditional correlation and covariance
gradientinstitute/causal-inspection pull request #42
Opened 2022-06-22 06:35 UTC by adaluong

* Returns a DataFrame instead of a ndarray if input Y is a DataFrame
* Includes labels from Y

2022-06-22 06:52 UTC, dsteinberg requested changes
Looks really good!
The only thing I would suggest is to explicitly test your type conversion code, see my inline comments for some suggestions.

2022-06-22 06:52 UTC, dsteinberg commented on cinspect/stats.py
> +        cov = _ndarray_to_df(cov, Y)
Very neat - I like this :-)

2022-06-22 06:52 UTC, dsteinberg commented on tests/test_stats.py
> +        calc_ccorr = calc_ccorr.to_numpy()
We may not need this since we control the type going into this test

2022-06-22 06:52 UTC, dsteinberg commented on tests/test_stats.py
> +        ccov = ccov.to_numpy()
See my previous comment.

Also, what may be worth doing, either in this function or later, is to explicitly test that if Y is a dataframe, that return type is a dataframe.

You could do something like:
```
Ydf = pd.DataFrame(Y, columns=["y", "z"])
... run the functions and test for the right output and column/index names
```

(I wouldn't bother re-testing the correct values are returned)

2022-06-27 02:46 UTC, adaluong commented
I've modified the function to only convert to a df if there's more than one column in Y and have added tests as requested @dsteinberg

2022-06-27 04:21 UTC, dsteinberg approved these changes
LGTM!

2022-06-27 04:21 UTC, merged